filter:
    paths:
        - src/*
    excluded_paths:
        - tests/*
checks:
    php:
        code_rating: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true
tools:
    external_code_coverage:
        timeout: 2100
    php_sim: false
    php_cpd: false
build:
    environment:
        php: 7.3.0
    services:
        mysql: 5.7
    nodes:
        tests-and-coverage:
            tests:
                override:
                    - vendor/bin/codecept run
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
    dependencies:
        before:
            - composer global require "fxp/composer-asset-plugin" --no-interaction
            - composer install --no-interaction
            - mysql -e "CREATE DATABASE scheduler_test;"
            - php tests/_app/yii migrate/up --interactive=0 --migrationPath=src/migrations/
            - vendor/bin/codecept build
checks:
    php: true
